name: Build es container image
on:
  push:
    paths:
      - .github/workflows/build-es-image.yml
      - nzws-etc/elastic-search/**/*

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: ./nzws-etc/elastic-search
          platforms: linux/amd64
          push: true
          tags: ghcr.io/nzws/elasticsearch-with-sudachi:latest
          cache-from: type=registry,ref=ghcr.io/nzws/elasticsearch-with-sudachi:latest
          cache-to: type=inline
